#!/bin/bash
#Author: Dennis Joson
#November 25, 2017
#script that check total memory usage

help() {
cat << END

Usage:
       check_mem3 -w <warning> -c <critical> -e <email address>
       OPTION
       ------------------------------------
       -h
       -w [VALUE]
       -c [VALUE]
       -e [valid email address]
Note: [VALUE] must be integer
END
}

while getopts "w:c:e:" opt
do
    case $opt in
      w) WARN="$OPTARG";;
      c) CRIT="$OPTARG";;
      e) EMAIL="$OPTARG";;
      #*) help;;
    esac
done

if [[ -z $CRIT || -z $WARN ]];
then
       echo "Must provide WARNING and CRITICAL values"
       help
elif [[ ! $CRIT =~ ^[0-9]+$ || ! $WARN =~ ^[0-9]+$ ]];
then
       echo "WARNING and CRITICAL must be integers"
       help
elif [[ $WARN -ge $CRIT ]];
then
       echo "WARNING must be bigger than CRITICAL value"
       help
elif [[ -z $EMAIL   ]];
then
       echo "Valid email address is required"
       help
fi

FreeM=`free -m`
TOTAL_MEMORY=`echo "$FreeM" |grep Mem |awk '{print $2}'`
USED=`echo "$FreeM" |grep Mem |awk '{print $3}'`
PER=`echo $((($USED*100)/$TOTAL_MEMORY))||cut -d. -f1`

OUTPUT=`echo "Total Memory= $TOTAL_MEMORY MB", "Used= $USED MB"`

if [ $PER -lt $WARN ];
then
    echo "OK - $OUTPUT"
    exit 0 
elif [[ $PER -ge $WARN && $PER -lt $CRIT ]];
then
    echo "WARNING - $OUTPUT"
    exit 1
else
    echo "CRITICAL - $OUTPUT"
    ps aux --sort -rss | head -10 | awk '{print $1, $2, $4, $11}' | mail -s  "`date +%Y%m%d` `date +%H:%M` memory check - critical"  $EMAIL
    exit 2 
fi
